# Generated by Django 4.0.4 on 2022-06-23 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_following_user_following_post_following_from_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='following',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
