# Generated by Django 4.0.4 on 2022-06-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_catagories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagories',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='current_price',
            new_name='starting_price',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='listing_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_description',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_image',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='listing',
            name='url',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
