# Generated by Django 4.0.4 on 2022-06-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
