# Generated by Django 4.0.4 on 2022-06-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_winner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
